### ISSUE TITLE
Alert shows on demo site for IE 9.

### ISSUE THREAD

**Issue by joshuapinter** [nmsdvid/ie-alert#10]
I used BrowserStack to view your [demo site](http://nmsdvid.com/iealert/example/index.html) with Internet Explorer 9 on a Windows 7 machine and it still popped up the dialog box. 

![screenshot 2015-01-07 08 57 22](https://cloud.githubusercontent.com/assets/180819/5648415/967eaa46-964b-11e4-8ee2-c35afed8aac7.png)

**Comment by nmsdvid** [comment]
thanks for the info, its fixed now. I made a mistake in the example site by calling the plugin on ie9 and below and not on ie8 and below. So the plugin works fine, I made an error.

**Comment by joshuapinter** [comment]
:+1: Thanks for fixing.
